name: absensi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
    sdk: ">=2.16.1 <3.0.0"

dependencies:
    cupertino_icons: ^1.0.2
    get: 4.6.5
    firebase_core: 2.1.0
    firebase_auth: 4.0.2
    flutter:
        sdk: flutter
    cloud_firestore: ^4.0.2
    firebase_storage: ^11.0.2

dev_dependencies:
    flutter_lints: ^1.0.0
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true
